name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.FORM_SUB_SSH_KEY }}

      - name: Copy files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -r ansible/web ubuntu@${{ secrets.FORM_SUB_PUBLIC_IP }}:/home/ubuntu/

      - name: Deploy container
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.FORM_SUB_PUBLIC_IP }} << 'EOC'
            cd /home/ubuntu/web
            CONTAINERS=$(sudo docker ps -q)
            if [ ! -z "$CONTAINERS" ]; then
              sudo docker stop $CONTAINERS
              sudo docker rm $CONTAINERS
            fi
            sudo docker build -t formsubapp .
            sudo docker run -d -p 80:80 formsubapp
          EOC
